### PR TITLE
Replace enacl with brine

### PR DESCRIPTION
**Pull request by drewkerrigan**
This change replaces enacl with [https://github.com/drewkerrigan/brine](https://github.com/drewkerrigan/brine).

The benefit is the ability to run navstar on a single CPU machine since it no longer requires dirty schedulers. (See https://dcosjira.atlassian.net/browse/DCOS-309 for an example of the issue).

### CODE REVIEW

**Comment by sargun** [comment]
Are the key formats equal?

**Comment by drewkerrigan** [comment]
@sargun Well, both have 32 byte secrets and 16 byte publics. Brine uses [ed25519](https://ed25519.cr.yp.to/), and nacl / libsodium is actually [moving to ed25519](https://nacl.cr.yp.to/sign.html) because it seems to be faster / more efficient. This is one of the primary reasons it enables us to get rid of dirty schedulers (speed).

```
1> rp(brine:new_keypair()).
#{handle => <<>>,
  public => <<40,163,83,207,40,147,122,124,205,38,143,134,77,110,137,
    128,141,0,36,218,133,245,102,94,20,58,45,46,89,100,160,
    140>>,
  secret => <<64,183,12,34,117,173,76,99,175,70,213,137,233,19,152,
    29,170,168,235,125,58,17,40,166,233,131,17,203,152,130,
    92,127,58,43,107,25,172,67,79,52,203,186,185,181,167,
    49,128,94,191,40,93,234,79,223,178,67,189,39,198,22,25,
    5,110,67>>}
```

From enacl:

```
1> rp(enacl:sign_keypair()).
#{public => <<233,37,189,242,192,185,112,163,175,96,106,151,153,152,
    3,228,86,199,71,44,80,94,249,191,59,43,213,82,218,167,
    25,222>>,
  secret => <<34,186,84,156,124,90,218,207,231,0,172,136,143,249,156,
    173,192,221,51,97,99,174,198,0,109,123,191,185,182,113,
    76,168,233,37,189,242,192,185,112,163,175,96,106,151,
    153,152,3,228,86,199,71,44,80,94,249,191,59,43,213,82,
    218,167,25,222>>}
```

When things calm down I can make a PR to DCOS to make sure everything lines up correctly, but theoretically everything should Just Work (tm)

**Comment by sargun** [comment]
We need to make sure for people's clusters that are already a thing, we can use existing keys.

**Comment by drewkerrigan** [comment]
Just an update on this - I wrote a quick test to compare enacl and brine... They're sort of compatible:

These tests pass: https://github.com/drewkerrigan/goldbug/blob/master/test/brine_vs_enacl_SUITE.erl#L133-L139

These do not: https://github.com/drewkerrigan/goldbug/blob/master/test/brine_vs_enacl_SUITE.erl#L141-L147

So in summary: 

| Public / Secret Keys | Signature | Verify | Pass/Fail |
| --- | --- | --- | --- |
| `brine` | `brine` | `brine` | **PASS** |
| `brine` | `brine` | `enacl` | **PASS** |
| `enacl` | `enacl` | `enacl` | **PASS** |
| `enacl` | `enacl` | `brine` | **PASS** |
| `brine` | `enacl` | `enacl` | **_FAIL**_ |
| `brine` | `enacl` | `brine` | **_FAIL**_ |
| `enacl` | `brine` | `enacl` | **_FAIL**_ |
| `enacl` | `brine` | `brine` | **_FAIL**_ |

I think more research is required before we can make a change like this because it depends on what libraries are being used to actually do the signature creation / verification.

**Pull request closed without merging**
